name: Build, Security Scan, and Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Update this to the version you're using

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release

    # Run tests (optional, include if you have tests)
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # Security scan using CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    # Tag the build if successful
    - name: Tag successful build
      if: success()
      run: |
        GIT_TAG="version-success-$(date +'%Y%m%d%H%M%S')"
        git tag $GIT_TAG
        git push origin $GIT_TAG

    # Tag the build if it fails
    - name: Tag failed build
      if: failure()
      run: |
        GIT_TAG="version-failed-$(date +'%Y%m%d%H%M%S')"
        git tag $GIT_TAG
        git push origin $GIT_TAG
